### ISSUE TITLE
QA Checks Report section in Part III needs updating

### ISSUE THREAD

**Issue by olejandro** [experimentarium/times#22]
Issues I've noticed:
- source code reference in text
- table probably doesn't contain recently added checks

**Comment by Antti-L** [comment]
Indeed, the QA checks section has not been updated lately.  I had not thought of that section needing to be updated, as the warnings/errors should be reasonably self-contained.
> could you take a look at this and confirm once https://github.com/experimentarium/times/pull/21 is merged?

Not sure what I should look at.  Anyway, the table in the document is at this point still not very readable (see below how it looks in my browser), and so I think the first priority would be to make it look better (or is it there more readable version published somewhere else?).

![image](https://github.com/experimentarium/times/assets/57945277/f14bb902-f8db-4fbf-bc68-1c2f9bbc79fa)

**Comment by olejandro** [comment]
Yes, once #21 is merged, the table will look like this https://times--21.org.readthedocs.build/en/21/part-3/02-model-run.html#times-qa-checks

I was specifically thinking of the QA checks you added after our recent discussion, probably in version 4.7.8, but I barely remember what it was about... :-(

Also the paragraph above the table refers to version 3.9.3. Should it be changed at least to 4.4.0?

**Comment by Antti-L** [comment]
Yes, it that has been clearly updated by me (to v4.4.0), but not after that.  
And yes, there were the recent IRE type check (for processes defined as IRE but not being trade processes).  But there have been several other QA additions since v4.4.0.  I can give you a list at a later time, if you would like to add them to the table.

**Comment by olejandro** [comment]
Sounds good, thanks!

**Comment by Antti-L** [comment]
I tried to check the additional QAs since v.4.4.0, and the attached file contains them:
[Additionla-QAs.docx](https://github.com/user-attachments/files/15534285/Additionla-QAs.docx)
@olejandro Could you convert them to the markdown source code format and add to the appropriate source file?

**Comment by olejandro** [comment]
Thanks @Antti-L! I've added the changes: https://github.com/experimentarium/times/pull/29/files

This is how the modified table will look after the corresponding PR is merged: https://times--29.org.readthedocs.build/en/29/part-3/02-model-run.html#times-qa-checks

Does it look okay? I've added the new entries at the bottom of the blocks of the corresponding types...

**Comment by Antti-L** [comment]
Yes, looks okay to me.
