### ISSUE TITLE
Some images have very poor quality due to conversion

### ISSUE THREAD

**Issue by Antti-L** [experimentarium/times#23]
Some images appear to have quite poor quality. I guess the reason for that is that all images have now been converted to bitmap images, while retaining the original **vector graphics**, when they were such, would result in much better quality. One example of a bad quality picture is below:
https://github.com/experimentarium/times/blob/main/docs/part-2/assets/image19.png
This image was well readable in the original document, being a vector graphics image. Is there some technical reason for converting the original vector graphics to poorer quality bitmap images? I think read-the-docs must be supporting vector images as well.

**Comment by olejandro** [comment]
Thanks @Antti-L! The images were converted to the current format with pandocs using default docx to md conversion settings. Let me investigate whether I can extract the images in different format.

**Comment by olejandro** [comment]
Ok, so I've manually converted most of the images in part 2 to svg e.g., see your original example rendered here: https://times--24.org.readthedocs.build/en/24/part-2/06-equations.html

Now I need to investigate why some of the images are not displayed though...

**Comment by olejandro** [comment]
Ah... It seems to be a cache thing! Ctrl+F5 resolves it on Firefox.

@Antti-L if you think it looks ok I can merge #24 already.

**Comment by Antti-L** [comment]
Indeed, many of the images look much better now.  So looks like well done!

**Comment by olejandro** [comment]
Ok, thanks! I've now converted some images in part 1, as well. Those that were embedded as pptx objects worked best. Will investigate what to do with images in part 2 which have increased their size a lot (causes long page load times).

**Comment by Antti-L** [comment]
Hmm... yes, I see the image files for Part II now summed up to **15 MB**, while the size of the **full docx file** was only 2 MB.  Looking inside the svg files created suggests that they may not employ vector graphics optimally after all.  Perhaps the conversion was not able to handle too well the conversion from the windows wmf/emf graphics (which are vector graphics) to svg?  But anyway, the good news is the better quality, which looks much closer to the original images.

**Comment by olejandro** [comment]
Ok, I've been through all of them one by one and made sure they were vector graphics instead of including a high resolution raster. The size is reasonable now. :-)
