### ISSUE TITLE
Provide link to the best-rendering version on readthedocs?

### ISSUE THREAD

**Issue by Antti-L** [experimentarium/times#33]
I have understood that the doc files may not rendering in the best way under Github, is that correct (and why is that so)?

However, as I know there is a supposedly best-rendering version somewhere out there, I have several times tried to search for it (with google), e.g.:

- `etsap times  site:readthedocs.com`
- `etsap times  site:readthedocs.io`
- `times  site:readthedocs.io`

For some reason, I never seem to find anything 😄 , and it is hard for me to remember the correct address. Therefore, it would help (for me at least) if the link would be given here (in readme.md).

**Comment by olejandro** [comment]
Thanks @Antti-L! I'll look into making the site more discoverable by google. 😄 Meanwhile here is the URL that will be added by the PR referencing this issue: https://times.readthedocs.io/

Regarding markdown rendering on GitHub, I think this section describes it quite well: https://www.markdownguide.org/getting-started/#flavors-of-markdown. We are using [MyST](https://myst-parser.readthedocs.io/) flavour in this project.

Actually, by any chance, could you take a look at [this section](https://times.readthedocs.io/en/latest/part-2/07-climate-module.html) of the docs and let me know what you think about it? Please disregard the equations at the end of the page that still don't break across the lines for now.

**Comment by Antti-L** [comment]
I had a brief look at [that section](https://times.readthedocs.io/en/latest/part-2/07-climate-module.html) and it looked quite good in general.  I did spot a few typographic issues, such as C\~S\~ → C<sub>S</sub> and CO\~2\~ → CO<sub>2</sub>, and so some more proofreading is needed.

**Comment by olejandro** [comment]
Super, thanks! I've fixed those now as well. As far as I can see there are no issues with subscripts left. (I am sure there are other issues though). Hopefully will be able to get many more eyes looking at the docs to get them completely polished.
